// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_on_widgets
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnDJmhwxSoLC6bf3Zc78e-yEfNWkAS6u0',
    appId: '1:196261243537:web:10809f57f0994b30f8ad30',
    messagingSenderId: '196261243537',
    projectId: 'gen-lang-client-0654629425',
    authDomain: 'gen-lang-client-0654629425.firebaseapp.com',
    storageBucket: 'gen-lang-client-0654629425.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnDJmhwxSoLC6bf3Zc78e-yEfNWkAS6u0',
    appId: '1:196261243537:android:placeholder', // Replace with actual Android App ID from Firebase Console
    messagingSenderId: '196261243537',
    projectId: 'gen-lang-client-0654629425',
    storageBucket: 'gen-lang-client-0654629425.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnDJmhwxSoLC6bf3Zc78e-yEfNWkAS6u0',
    appId: '1:196261243537:ios:placeholder', // Replace with actual iOS App ID from Firebase Console
    messagingSenderId: '196261243537',
    projectId: 'gen-lang-client-0654629425',
    storageBucket: 'gen-lang-client-0654629425.firebasestorage.app',
    iosBundleId: 'com.example.nutrisnapAi',
  );
}
