// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_on_widgets
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnDJmhwxSoLC6bf3Zc78e-yEfNWkAS6u0',
    appId: '1:799302501650:web:placeholder', // Update this from your Firebase Web App settings
    messagingSenderId: '799302501650',
    projectId: 'nutrisnap-3bf24',
    authDomain: 'nutrisnap-3bf24.firebaseapp.com',
    storageBucket: 'nutrisnap-3bf24.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnDJmhwxSoLC6bf3Zc78e-yEfNWkAS6u0',
    appId: '1:799302501650:android:5befcaa0cef90b27fd5fcb',
    messagingSenderId: '799302501650',
    projectId: 'nutrisnap-3bf24',
    storageBucket: 'nutrisnap-3bf24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnDJmhwxSoLC6bf3Zc78e-yEfNWkAS6u0',
    appId: '1:799302501650:ios:placeholder', // Update this from your Firebase iOS App settings
    messagingSenderId: '799302501650',
    projectId: 'nutrisnap-3bf24',
    storageBucket: 'nutrisnap-3bf24.appspot.com',
    iosBundleId: 'nutrisnap.sri',
  );
}
